# Generated by Django 5.0.6 on 2024-05-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.IntegerField(unique=True)),
                ("email", models.EmailField(max_length=255)),
                ("address", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
