# Generated by Django 5.0.6 on 2024-05-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
