# Generated by Django 5.0.6 on 2024-05-17 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_products_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={"ordering": ("id",)},
        ),
    ]
